[2023-10-02 15:23:38,613] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2023-10-02T15:23:37.322394+00:00 [queued]>
[2023-10-02 15:23:38,622] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2023-10-02T15:23:37.322394+00:00 [queued]>
[2023-10-02 15:23:38,623] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-02 15:23:38,625] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-02 15:23:38,626] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-02 15:23:38,640] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): load_seed_data_once> on 2023-10-02 15:23:37.322394+00:00
[2023-10-02 15:23:38,645] {standard_task_runner.py:52} INFO - Started process 602 to run task
[2023-10-02 15:23:38,647] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', '1_init_once_seed_data', 'load_seed_data_once', 'manual__2023-10-02T15:23:37.322394+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/init.py', '--cfg-path', '/tmp/tmpzn0hgyia', '--error-file', '/tmp/tmp5w9a7p3k']
[2023-10-02 15:23:38,648] {standard_task_runner.py:80} INFO - Job 16: Subtask load_seed_data_once
[2023-10-02 15:23:38,699] {task_command.py:369} INFO - Running <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2023-10-02T15:23:37.322394+00:00 [running]> on host c2e542998ec2
[2023-10-02 15:23:38,801] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=1_init_once_seed_data
AIRFLOW_CTX_TASK_ID=load_seed_data_once
AIRFLOW_CTX_EXECUTION_DATE=2023-10-02T15:23:37.322394+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-02T15:23:37.322394+00:00
[2023-10-02 15:23:38,802] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-10-02 15:23:38,804] {subprocess.py:74} INFO - Running command: ['bash', '-c', '(cd dbt_snowflake) -and (dbt seed --profiles-dir .)']
[2023-10-02 15:23:38,812] {subprocess.py:85} INFO - Output:
[2023-10-02 15:23:38,813] {subprocess.py:92} INFO - bash: -c: line 1: syntax error near unexpected token `-and'
[2023-10-02 15:23:38,814] {subprocess.py:92} INFO - bash: -c: line 1: `(cd dbt_snowflake) -and (dbt seed --profiles-dir .)'
[2023-10-02 15:23:38,814] {subprocess.py:96} INFO - Command exited with return code 2
[2023-10-02 15:23:38,829] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-10-02 15:23:38,833] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=1_init_once_seed_data, task_id=load_seed_data_once, execution_date=20231002T152337, start_date=20231002T152338, end_date=20231002T152338
[2023-10-02 15:23:38,845] {standard_task_runner.py:97} ERROR - Failed to execute job 16 for task load_seed_data_once (Bash command failed. The command returned a non-zero exit code 2.; 602)
[2023-10-02 15:23:38,861] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-10-02 15:23:38,891] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
