[2023-10-02 15:28:22,890] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2023-10-02T15:28:21.604724+00:00 [queued]>
[2023-10-02 15:28:22,901] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2023-10-02T15:28:21.604724+00:00 [queued]>
[2023-10-02 15:28:22,902] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-02 15:28:22,904] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-02 15:28:22,905] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-02 15:28:22,920] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): load_seed_data_once> on 2023-10-02 15:28:21.604724+00:00
[2023-10-02 15:28:22,925] {standard_task_runner.py:52} INFO - Started process 842 to run task
[2023-10-02 15:28:22,928] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', '1_init_once_seed_data', 'load_seed_data_once', 'manual__2023-10-02T15:28:21.604724+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/init.py', '--cfg-path', '/tmp/tmpu31126ha', '--error-file', '/tmp/tmp9f2dka1i']
[2023-10-02 15:28:22,929] {standard_task_runner.py:80} INFO - Job 20: Subtask load_seed_data_once
[2023-10-02 15:28:22,977] {task_command.py:369} INFO - Running <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2023-10-02T15:28:21.604724+00:00 [running]> on host c2e542998ec2
[2023-10-02 15:28:23,072] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=1_init_once_seed_data
AIRFLOW_CTX_TASK_ID=load_seed_data_once
AIRFLOW_CTX_EXECUTION_DATE=2023-10-02T15:28:21.604724+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-02T15:28:21.604724+00:00
[2023-10-02 15:28:23,073] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-10-02 15:28:23,075] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd ../dbt_snowflake && dbt seed --profiles-dir .']
[2023-10-02 15:28:23,082] {subprocess.py:85} INFO - Output:
[2023-10-02 15:28:23,083] {subprocess.py:92} INFO - bash: line 1: cd: ../dbt_snowflake: No such file or directory
[2023-10-02 15:28:23,084] {subprocess.py:96} INFO - Command exited with return code 1
[2023-10-02 15:28:23,098] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-10-02 15:28:23,102] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=1_init_once_seed_data, task_id=load_seed_data_once, execution_date=20231002T152821, start_date=20231002T152822, end_date=20231002T152823
[2023-10-02 15:28:23,114] {standard_task_runner.py:97} ERROR - Failed to execute job 20 for task load_seed_data_once (Bash command failed. The command returned a non-zero exit code 1.; 842)
[2023-10-02 15:28:23,142] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-10-02 15:28:23,170] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
